### ISSUE TITLE
Preload causes the keyboard to show up for a split second on appstart

### ISSUE THREAD

**Issue by pvinis** [kirillzyusko/react-native-keyboard-controller#1077]
**Describe the bug**
Since updating to the version with preload, we see the keyboard show up for a bit while the app is showing the splashscreen.

**Code snippet**
N/A

**Repo for reproducing**
Nothing besides the install and the `KeyboardProvider` wrapper. Preload is on by default.

**To Reproduce**

**Expected behavior**
I would expect the keyboard to not show up.

**Screenshots**

https://github.com/user-attachments/assets/1e78f773-dfd8-48e1-ba5c-42a7cd61a398

**Smartphone (please complete the following information):**

- Desktop OS: [e.g. Windows 10, MacOS 10.15.5]
- Device: [e.g. iPhone8]
- OS: [e.g. iOS 10.0]
- RN version: [e.g. 0.68.2]
- RN architecture: [e.g. old/new or paper/fabric]
- JS engine: [e.g. JSC, Hermes, v8]
- Library version: [e.g. 1.2.0]

**Additional context**

**Comment by kirillzyusko** [comment]
Interesting 🤔 

Is it because of biometric screen? I haven't seen such behavior in other apps

The one thing I can recommend is to disable preload via `preload={false}` prop on `KeyboardProvider` level 🤔

**Comment by kirillzyusko** [comment]
What would happen, if you disable it on provider level, but call this method after passing biometric verification? Or a second later?

What would happen if you call 

```tsx
useEffect(() => {
  KeyboardController.preload();
}, []):
```

or something like this when a Wallet screen becomes actually visible?

**Comment by pvinis** [comment]
We are testing that right now. Ill update as we have news. I could not repro on my device so testing is a bit slower as we need a build etc.

For now I tried to preload={false} and see if that makes it not appear.

Then ill try the useEffect.

**Comment by pavlos-sqds** [comment]
with preload false, we def do not get that keyboard. flashing. trying soon the useEffect.

**Comment by pavlos-sqds** [comment]
seems like the useeffect after the splashscreen is done makes it work fine. still, probably that shouldnt happen with default preload.

feel free to keep this issue open or close.

**Comment by kirillzyusko** [comment]
@pavlos-sqds so do I correctly understand that you propose to disable keyboard preloading by default and allow users to specify `preload` to `true` if they want?

The idea was to give kind of preloading benefit by default, but if it causes undesired behavior then give an opportunity to disable preloading and manage it manually (if needed).

In your opinion - what is the correct way to fix this issue? The problem is that if turn it on by default, then some users may see unexpected behavior. If turn it off by default, then users will have to manually enable it and I know that some people will not be aware about it and will skip this optimization 🤔

**Comment by pavlos-sqds** [comment]
ah no, im not saying that. preload should be default on, for sure.

what im saying is that this weird flashing issue should be fixed.

firstly, because this issue seems to be not too simple, and it involves ios stuff that you dont have control over, it would be a good idea to have the suggestion in the docs. something along the lines of "if the keyboard pops up while your app is still loading, disable preload and preload in a useEffect."

secondly, it would be nice to investigate what the issue is here, but i understand that it might be hard to repro, or even debug. but if you think you have some idea why that might have happened to our app with the preload enabled, thats probably worth playing around with.

thoughts?

**Comment by kirillzyusko** [comment]
@pavlos-sqds yeah, it totally makes sense what you are saying. I added a note in documentationa bout the side effect and how to avoid it in #1149 

> secondly, it would be nice to investigate what the issue is here, but i understand that it might be hard to repro, or even debug. but if you think you have some idea why that might have happened to our app with the preload enabled, thats probably worth playing around with.

I think it's just because you request biometric authentication and I try to create an input, request focus programmatically and I think iOS just doesn't handle the priority well between windows and you see this flicker. I can't really help here a lot. The best fix for you is to disable automatic preload and do a manual preload when you pass biometric authentication (what you already do, I guess).

Thank you for the issue - I hope other people who encounter this problem will already know what to do in order to resolve this conflict.

**Comment by jstnw10** [comment]
Just figured out how to reproduce it reliably, even without biometric authentication requests. It still occurs only when `preload` is not set to `false` on the provider.

It happens on app launch when the app is launched from Spotlight while the keyboard is already open.

This issue does not occur when:

- App is started from homescreen
- App is started from app library
- App is started from spotlight but keyboard is closed
- App is started from app library search while keyboard is open

**Comment by kirillzyusko** [comment]
Hey @jstnw10 

Could you please attach a video? 🙏 

I think I don't understand the difference between app library vs spotlight. Does it happen on simulator as well or do I need to use physical device for that? Which iOS version do you use and which phone do you use?

**Comment by jstnw10** [comment]
Hey @kirillzyusko, sure :)

Spotlight:

https://github.com/user-attachments/assets/9891de7e-439d-4ed5-9ad1-548454a85d7f

App Library:

https://github.com/user-attachments/assets/06430570-7843-4cd0-bb49-3baaced00c47

I didn't have time to test this on a simulator yet, this is from a physical device. These are prod builds of an example app having this issue. Also as mentioned, this keyboard flash only happens via keyboard open in spotlight as far as I know. Launching an app from anywhere else doesn't seem to have this issue.

**Comment by kirillzyusko** [comment]
@jstnw10 just tested it on physical iPhone 16 Pro (iOS 26.6.1) and I can not reproduce in fabric/release example app 🤷‍♂️ 

https://github.com/user-attachments/assets/c65deff2-f18d-4a46-81bc-02849c489f84

Any ideas what I'm doing wrong?..
