### ISSUE TITLE
Blank space upon closing the keyboard on few android versions

### ISSUE THREAD

**Issue by vineelk8** [kirillzyusko/react-native-keyboard-controller#1091]
**Describe the bug**
I have upgraded my project to support Android 15 SDK. After the upgrade, we are facing multiple issues with the keyboard opening and closing. Below are the details for the issue

**Code snippet**
Here is the complete code to reproduce it
```
import React from 'react';
import { StyleSheet, Text, TextInput, View } from 'react-native';
import {
  KeyboardAwareScrollView,
  KeyboardStickyView,
} from 'react-native-keyboard-controller';

const SmapleScreen = () => {
  return (
    <View style={styles.container}>
      <View style={styles.header}>
        <Text style={styles.headerText}>Comments List</Text>
      </View>
      <KeyboardAwareScrollView contentContainerStyle={{ paddingBottom: 100 }}>
        {Array.from({ length: 20 }).map((_, i) => {
          return (
            <View key={String(i)} style={styles.commentBox}>
              <Text style={{ color: 'black' }}>{`Comment ${i}`}</Text>
            </View>
          );
        })}
      </KeyboardAwareScrollView>
      <KeyboardStickyView offset={200} style={styles.inputWrapper}>
        <TextInput
          placeholder="Write a reply..."
          style={styles.input}
          multiline
        />
      </KeyboardStickyView>
    </View>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fafafa',
  },
  header: {
    padding: 16,
    backgroundColor: '#fff',
    borderBottomWidth: 1,
    borderBottomColor: '#ddd',
  },
  headerText: {
    fontSize: 16,
    fontWeight: '600',
  },
  commentBox: {
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#eee',
    backgroundColor: '#fff',
  },
  inputWrapper: {
    bottom: 45,
    backgroundColor: '#fff',
    padding: 10,
    borderTopWidth: 1,
    borderColor: '#ddd',
  },
  input: {
    height: 45,
    borderWidth: 1,
    borderRadius: 8,
    borderColor: '#ccc',
    paddingHorizontal: 10,
    backgroundColor: '#fff',
  },
});

export default SmapleScreen;
```

**To Reproduce**

- Project should support Android 15 (35)
- Use the library versions as mentioned below in the project
- Wrap the navigation in App.js as below
```
import React from 'react';
import { KeyboardProvider } from 'react-native-keyboard-controller';
import { NotifierWrapper } from 'react-native-notifier';

import AppNavigator from './src/navigation/AppNavigator';

const App = () => {
  return (
    <NotifierWrapper>
      <KeyboardProvider>
        <SafeAreaProvider initialMetrics={initialWindowMetrics}>
          <AppNavigator />
        </SafeAreaProvider>
      </KeyboardProvider>
    </NotifierWrapper>
  );
};

export default App;

```
- Create a screen with the above shared code
- Click inside the text input, the keyboard opens, then close it manually upon touching anywhere on the screen. Now the blank space is visible as shown in the recording. The blank space will be visible till the app is reopened

**Expected behavior**
On the keyboard, opening and closing the screen should adjust back to the normal position without any blank space

**Screenshots**
Here is the recording for the issue

https://github.com/user-attachments/assets/aca80451-d9c8-4a40-a854-9133439b716c

**Smartphone (please complete the following information):**

- Device: OnePlus Nord2 5G
- OS: Android 13 (OxygenOS)
- RN version: 0.74.6
- Library versions:
       "react": "18.2.0",
       "react-native": "0.74.6",
       "react-native-edge-to-edge": "^1.6.2",
       "react-native-safe-area-context": "^5.5.2",
       "react-native-keyboard-controller": "^1.18.5",
       "react-native-notifier": "^2.0.0"

**Comment by adamgeorgsson** [comment]
I'm facing the same symptoms but with different conditions. I will open a new issue if it turns out to be another root cause.

Android sdk version: 32 and lower (doesn't matter if I build with targetSdkVersion 34 or 35)

I can reproduce with example app with some code changes shown below.

**git diff in example app**
```
diff --git a/example/android/app/src/main/res/values/styles.xml b/example/android/app/src/main/res/values/styles.xml
index d653a97ac..3c1e5c55f 100644
--- a/example/android/app/src/main/res/values/styles.xml
+++ b/example/android/app/src/main/res/values/styles.xml
@@ -2,6 +2,7 @@
 
     <!-- Base application theme. -->
     <style name="AppTheme" parent="Theme.AppCompat.DayNight.NoActionBar">
+        <item name="android:windowFullscreen">true</item>
         <!-- Customize your theme here. -->
         <item name="android:editTextBackground">@drawable/rn_edit_text_material</item>
 
diff --git a/example/src/App.tsx b/example/src/App.tsx
index 55eea052c..ebcafbef6 100644
--- a/example/src/App.tsx
+++ b/example/src/App.tsx
@@ -37,6 +37,10 @@ const linking = {
 const spinner = <ActivityIndicator color="blue" size="large" />;
 
 export default function App() {
+  React.useEffect(() => {
+    StatusBar.setHidden(false);
+  }, []);
+
   return (
     <SafeAreaProvider initialMetrics={initialWindowMetrics}>
       <GestureHandlerRootView style={styles.root}>
```

The bug shows only when both `android:windowFullscreen` and `StatusBar.SetHidden(false)` are used together. I honestly don't know if we need android:windowFullscreen anymore. I think we added it to hide statusbar when splash screen shows but the splash screen isn't working at the moment anyway. I also tried to replace StatusBar static API with the component but stumbled upon another bug which I will open another issue for if I manage to reproduce it in the example app.

**Reproducable example**
From example 6. Aware scroll view sticky footer:
  1. Scroll down to text input # 9 and press. Gap appear
  2. Press on close keyboard. Gap disappear
  3. Press input # 9 again. Gap appear
  4. Press area between input # 8 and input # 9. Gap stays and changes color
  5. Press input # 9 again. Gap appear
  6. Press input # 8. Gap disappear

**Screen record on Pixel_6_Pro_API_32:**

https://github.com/user-attachments/assets/aabb7140-7a27-4aaf-adec-114e1da36a3a

**Comment by tj-mc** [comment]
Also experiencing this when upgrading to Expo 53

**Comment by tj-mc** [comment]
@Ejdamm thank you for your tip on StatusBar. 

I experienced the bug, identical to how @vineelk8 recorded. When I removed manual status bar hide/show in my app, it was resolved.

**Comment by kirillzyusko** [comment]
Thanks @Ejdamm for describing the problem and providing a reproducible example!

I think @vineelk8 and you indeed have the same symptoms. For me it looks like Android tries to avoid keyboard itself + keyboard-controller also handles that - and because of that you get double avoiding (you can also see how your header moves up when keyboard gets shown).

Similar behavior can be reproducible if you set `adjustPan` (and don't switch it to `adjustResize`, though lib does it automatically so most likely it's not the case).

I'll try to look into the problem, why it happens exactly!

**Comment by kirillzyusko** [comment]
Okay, the problem happens because of a race condition. I mount `edge-to-edge` view later, but receive call to `setHidden` earlier 🤔 

I attempted to fix it in https://github.com/kirillzyusko/react-native-keyboard-controller/issues/993#issuecomment-3167341405

But it looks like we need more reliable solution 👀

**Comment by kirillzyusko** [comment]
@Ejdamm @tj-mc @vineelk8 can you check if it fixes the problem?

https://github.com/kirillzyusko/react-native-keyboard-controller/pull/1098

**Comment by adamgeorgsson** [comment]
> [@Ejdamm](https://github.com/Ejdamm) [@tj-mc](https://github.com/tj-mc) [@vineelk8](https://github.com/vineelk8) can you check if it fixes the problem?
> 
> [#1098](https://github.com/kirillzyusko/react-native-keyboard-controller/pull/1098)

Works like a charm

```
package.json

"react-native-keyboard-controller": "https://github.com/kirillzyusko/react-native-keyboard-controller.git#fix\/clear-legacy-full-screen-flag",
```

**Comment by kirillzyusko** [comment]
Amazing! I merged PR and will publish a new version with fix in first days of September!

Let me know if you encounter any issues with the new version. And if so then feel free to open a new issue with reproduction.

Sorry for ghosting this issue a little bit - I was on a vacation (and still kind of on a vacation), but will return to work soon and will give a better support for this package!

**Comment by kirillzyusko** [comment]
Fix published in `1.18.6` 🙌 

Let me know if you keep encounter any issues!

**Comment by hakanolgun** [comment]
Hi @kirillzyusko, thank you for this amazing library.

I upgraded the package version to 1.18.6 but I noticed that this issue still happening on android 14 (sdk 34) phones. It is only happening on release mode, generated apk.

android 15 - debug mode > OK
android 15 - release mode > OK

android 14 - debug mode > OK
android 14 - release mode > FAIL (Sometimes)

As you said before it is something like a race condition. because it is not happening all the time in android 14 release mode. sometimes works sometimes not.

before 1.18.6 version it was happening all the time on android 14 devices.

<img width="200" height="444" alt="Image" src="https://github.com/user-attachments/assets/f259f34d-9d39-4eb3-9e6e-781e0af28642" />

<img width="200" height="444" alt="Image" src="https://github.com/user-attachments/assets/d312b41f-5814-4427-847b-f56f7481dab7" />
