### ISSUE TITLE
`KeyboardAvoidingView` does not work on iOS 26 specifically in TestFlight

### ISSUE THREAD

**Issue by sidorchukandrew** [kirillzyusko/react-native-keyboard-controller#1138]
**Describe the bug**
Specifically on iOS 26, in TestFlight, `<KeyboardAvoidingView />` is not animating its values as the keyboard opens. When the keyboard finishes opening, then the keyboard avoidance finally works.

**Code snippet**

**Repo for reproducing**
I'm so sorry, but this isn't reproducible in a local environment or even a Firebase build. This seems to only happen in TestFlight. We haven't published to production, so we're not sure if this is a problem on the actual App Store.

**To Reproduce**
I hope the additional context makes up for not being able to provide a reproducible 🙏 Please read at the bottom 🙏 

**Expected behavior**

**Screenshots**
<video src="https://github.com/user-attachments/assets/5d30e90d-4851-483a-9979-e4cba0a7b665" width="400px" />

**Smartphone (please complete the following information):**

- Desktop OS: _unrelated_
- Device: iPhone 12 Pro
- OS: iOS 26
- RN version: 0.79.6
- RN architecture: old
- JS engine: Hermes
- Library version: 1.18.5

**Additional context**
🚨🚨🚨
Here is the important information from what I could track down!

1. KeyboardAvoidingView uses `useKeyboardAnimation` to track the height [here](https://github.com/kirillzyusko/react-native-keyboard-controller/blob/main/src/components/KeyboardAvoidingView/index.tsx#L98)
2. `useKeyboardAnimation` uses `useKeyboardHandler` to listen to height events [here](https://github.com/kirillzyusko/react-native-keyboard-controller/blob/main/src/components/KeyboardAvoidingView/hooks.ts#L29)
3. `useKeyboardHandler` uses `useGenericKeyboardHandler` [here](https://github.com/kirillzyusko/react-native-keyboard-controller/blob/main/src/hooks/index.ts#L157)
4. `useGenericKeyboardHandler` uses `useKeyboardContext` [here](https://github.com/kirillzyusko/react-native-keyboard-controller/blob/main/src/hooks/index.ts#L157)
5. `useKeyboardContext` has its provider defined in `animated.tsx` [here](https://github.com/kirillzyusko/react-native-keyboard-controller/blob/main/src/animated.tsx#L113)
6. `animated.tsx` actually just uses `reanimated.native.tsx` [here](https://github.com/kirillzyusko/react-native-keyboard-controller/blob/main/src/animated.tsx#L187)
7. `reanimated.native.tsx` uses `useEvent` from reanimated to listen for "move" events [here](https://github.com/kirillzyusko/react-native-keyboard-controller/blob/main/src/reanimated.native.ts#L36)

And here is the problem! Reanimated also suffers from iOS 26 not firing move events. There is an open PR with reanimated [here](https://github.com/software-mansion/react-native-reanimated/issues/8270)

**Comment by tom-at-pixel** [comment]
I'm experiencing this problem in TestFlight (not sure about production) on iPhone 17 Pro running iOS 26.0.1. It works fine on the simulator (same iPhone and same OS) and for older iPhones running the same iOS.

**Comment by kirillzyusko** [comment]
Hey @sidorchukandrew 

Appreciate the effort you put into this issue ♥️

I believe this issue is a different one, than was linked from a reanimated repo (in short - we use different implementations, so symptoms may be similar, but root cause will be different).

I have seen a similar issue in https://github.com/kirillzyusko/react-native-keyboard-controller/issues/338 - but when I build the app and upload it to TestFlight, then everything was working well 🤯

From my past experience this problem may be heavily dependent on the app structure itself and linked dependencies. For example in the past I had an issue, that after opening in-app browser keyboard tracking was stopping working.

So that's being said - I need a reproduction app with full environment to be able to fix this issue 😓I understand that it may be very hard to prepare such reproduction repo, but maybe you or @tom-at-pixel can invite me into your project, so that I can generate builds on my own and test what's going wrong?

Alternatively we can have a conversation in discord and I will tell you steps that I would try to do and you will assemble a build/perform tests/say result back to me and we'll repeat process over and over.

Let me know what you think about this 👀

**Comment by kirillzyusko** [comment]
I'm fine to sign any kind of agreement, that I will not steal the code, re-distribute it, steal the idea of the app etc.

The issue is that the problem is a very complex and it may affect a lot of other developers. So I'm just trying to find a way which will work for both of us 🙃

**Comment by sidorchukandrew** [comment]
You sir are an absolute boss. So quick to answer and so willing to help even without a repro. I'm going to talk it over with my boss tomorrow to see his thoughts!

**Comment by tom-at-pixel** [comment]
Following up on my previous comment: after reinstalling my app, I’m seeing the same issue (no animations) on older iPhones running the latest iOS. If I have time tomorrow I’ll create a minimal repro.

**Comment by sidorchukandrew** [comment]
I won't be able to share the entire repo with you, but I'm going to clone it with all its dependencies and reduce down the source files to the bare minimum to reproduce it.

Some more findings also:

We bumped our Macos runner to 15 on GitHub and used Xcode 16.4. When you install the app for the first time, it still has the issue. If you restart the app, it animates correctly. Previously, we were on Macos runner 14 and Xcode 16.2. In that version, the animations didn't work no matter how many times you restart the app.

**Comment by sidorchukandrew** [comment]
I even tried with Macos 26 and Xcode 26. I see the new keyboard, but experience the same thing were the first app launch, the keyboard is broken. App restarts, the keyboard is fixed. I'm just leaving these details here in case it helps. I'll post back later with the repo

**Comment by sidorchukandrew** [comment]
Haha nevermind, now it's deciding to just be permanently broken, regardless of what build I use! Anyways, I'll post back with the repo later still.

**Comment by kirillzyusko** [comment]
> We bumped our Macos runner to 15 on GitHub and used Xcode 16.4. When you install the app for the first time, it still has the issue. If you restart the app, it animates correctly. Previously, we were on Macos runner 14 and Xcode 16.2. In that version, the animations didn't work no matter how many times you restart the app.
>
> I even tried with Macos 26 and Xcode 26. I see the new keyboard, but experience the same thing were the first app launch, the keyboard is broken. App restarts, the keyboard is fixed. I'm just leaving these details here in case it helps. I'll post back later with the repo

Yeah, it looks like I can not pick up a proper keyboard view for the first time 😠 Don't know exactly why, but maybe app is getting wrapped into an additional window or something like that... Hard to say without inspecting view hierarchy 😓 

> Anyways, I'll post back with the repo later still.

Looking forward to it! 👀

**Comment by kirillzyusko** [comment]
@sidorchukandrew on the video in the first message in the issue - do you use modals by any chance?

**Comment by sidorchukandrew** [comment]
Sorry for not getting the minimal repro example yet! These are not modals, they are just navigating between 2 different react navigation screens.

**Comment by kirillzyusko** [comment]
@sidorchukandrew I published `1.19.1` where made some important changes. Please, test this version in your app 🙏 

If it doesn't fix the problem, then please provide a repro - will be happy to look into the problem!

**Comment by joacub** [comment]
yeah, in testflight also this version is having a crash sometimes when clicking in a button with the keyboard open, it is not constantly is sometimes

**Comment by tom-at-pixel** [comment]
I can confirm that animations in TestFlight are working again in the latest version! Thank you. 🙏

**Comment by kirillzyusko** [comment]
@joacub could you please create a new issue and describe which exactly version and which crash it produces?

@tom-at-pixel wow, glad it was fixed! Let's also wait for @sidorchukandrew feedback 👀

**Comment by joacub** [comment]
> [@joacub](https://github.com/joacub) could you please create a new issue and describe which exactly version and which crash it produces?
> 
> [@tom-at-pixel](https://github.com/tom-at-pixel) wow, glad it was fixed! Let's also wait for [@sidorchukandrew](https://github.com/sidorchukandrew) feedback 👀

done https://github.com/kirillzyusko/react-native-keyboard-controller/issues/1168

**Comment by kirillzyusko** [comment]
@sidorchukandrew Also it's better to test with `1.19.2` (since `1.19.1` has some critical bugs). But if `1.19.2` doesn't fix the problem, then please test `1.19.1` too (it'll help in further debugging).

**Comment by kirillzyusko** [comment]
@sidorchukandrew also please re-test on `1.19.4` too 🙏  A similar issue has been reported in https://github.com/kirillzyusko/react-native-keyboard-controller/issues/1182 and has been fixed in `1.19.4`, so I suspect that `1.19.4` may fix this problem too!

**Comment by kirillzyusko** [comment]
@sidorchukandrew Better to test on `1.19.5` - the `1.19.4` still may stop working randomly, but `1.19.5` should fix all these issues!

**Comment by sidorchukandrew** [comment]
These two versions both seem to work! I'm still seeing some jitteriness (like the animated values aren't smooth, maybe too few), but I may come around to opening a different issue. Thank you for fixing this!
