### ISSUE TITLE
[IOS] Incorrect behavior of hooks and components when focusing on an input with secureTextEntry enabled.

### ISSUE THREAD

**Issue by A-Yatsyk** [kirillzyusko/react-native-keyboard-controller#327]
**Describe the bug**

When focusing on a field with **secureTextEntry** set to **true** **(iOS only)**, UI misbehaves with **KeyboardAvoidingView**, causing erratic jumping. In **useKeyboardHandler**, onStart will be called with progress 1, followed immediately by onEnd with progress 1, and only after these _(prior onStart and onEnd)_ will correct calls of onStart, onMove, and onEnd occur.
This behavior is also observed in **KeyboardEvents**, where the first listener is wrong, and only after that, do true listener calls follow.

A similar issue was present in React-Native itself, but it was fixed since KeyboardAvoidingView in React-Native now works as expected for iOS _(e.g., https://github.com/facebook/react-native/issues/39411)_.

**Code snippet**

```
<KeyboardAvoidingView
      behavior="padding"
      style={{ flex: 1 }}
      contentContainerStyle={{ flexGrow: 1 }}
>
    <SafeArea style={{ flex: 1 }}>
        <ScrollView
            bounces={false}
            style={{ flex: 1 }}
            keyboardShouldPersistTaps="handled"
            contentContainerStyle={{ flexGrow: 1, paddingHorizontal: 25 }}
        >
            <View style={{ flex: 2 }} />

            <TextInput
                placeholder="Placeholder"
                secureTextEntry
                style={{
                    height: 45,
                    borderWidth: 1,
                    borderColor: 'gray',
                    borderRadius: 10,
                    paddingHorizontal: 10,
                }}
            />

            <View style={{ flex: 1 }} />

            <View style={{ alignItems: 'center' }}>
                <Text>Footer</Text>
          </View>
        </ScrollView>
    </SafeArea>
</KeyboardAvoidingView>
```

**To Reproduce**

1. Add **secureTextEntry** with a value of **true** to the field.
2. Wrap the screen using **KeyboardAvoidingView**.
3. Focus on the field with a closed keyboard.

**OR**

1. Add **secureTextEntry** with a value of **true** to the field.
2. Add **useKeyboardHandler** with handlers for **onStart**, **onMove**, **onEnd** using console.log.
3. Focus on the field with a closed keyboard _(the first onStart and onEnd won't reflect reality)_

**Expected behavior**

Expected behavior should be the same as when the **secureTextEntry** is set to **false**

**Screenshots**

https://github.com/kirillzyusko/react-native-keyboard-controller/assets/20336643/652eeb47-ad3f-47e9-adc5-2c3e404e1feb

**Smartphone:**

- Desktop OS: MacOS 14.2.1
- Device: iPhone15
- OS: iOS 17.2
- RN version: 0.70.13
- RN architecture: paper (old)
- JS engine: Hermes
- Library version: 1.10.1

**Comment by oleksandr-dziuban** [comment]
Same issue

**Comment by kirillzyusko** [comment]
Interesting, I think this bug was introduced in iOS 17. A similar issue was raised quite long time ago: https://github.com/kirillzyusko/react-native-keyboard-controller/issues/243

But I'll have a look on it 👀

**Comment by A-Yatsyk** [comment]
> Interesting, I think this bug was introduced in iOS 17. A similar issue was raised quite long time ago: #243
> 
> But I'll have a look on it 👀

Thank you, as this is a critical issue for working with animations. If we take into account useKeyboardHandler, KeyboardAvoidingView can be replaced with the one from the "react-native" package (for iOS for now).🤞

This library is the only one that truly helps interact with the keyboard for animations. The rest are too buggy. 😅

**Comment by kirillzyusko** [comment]
@A-Yatsyk does this problem happens on `1.10.0`? It seems like the problematic code was introduced in https://github.com/kirillzyusko/react-native-keyboard-controller/pull/316, am I right?

**Comment by A-Yatsyk** [comment]
> @A-Yatsyk it should be fixed in #331 can you please check? 👀

This is better than it was. If you watch the video, you can see that there are still occasional glitches. We still have duplications of onStart/onEnd handler calls.

https://github.com/kirillzyusko/react-native-keyboard-controller/assets/20336643/7b32eaf6-0a22-454d-bba7-1acc73e7ed8c

**Comment by A-Yatsyk** [comment]
@kirillzyusko at the moment when glitches occur in KeyboardAvoidingView, in the logs for useKeyboardHandler, you can observe the following:

1. onStart => { height: 291, progress: 1, ... }
2. onEnd => { height: 291, progress: 1, ... }
3. onStart => { height: 336, progress: 1, ... }
4. onMove => { height: 49.28188181016594, progress: 0.14667226729216054, ... }
..........
5. onMove => { height: 336, progress: 1, ... }
6. onEnd => { height: 336, progress: 1, ... }

**Comment by kirillzyusko** [comment]
Yes @A-Yatsyk 

If you add `keyboardWillShow` listener to plain react-native module, you'll also see that native side is emitting this additional event:

```bash
 LOG  onStart {"duration": 250, "eventName": "onKeyboardMoveStart", "height": 291, "progress": 1, "target": 473}
 LOG  keyboardWillShow 291
 LOG  onStart {"duration": 250, "eventName": "onKeyboardMoveStart", "height": 336, "progress": 1, "target": 473}
 LOG  keyboardWillShow 336
```

The thing is that I can not filter out bad event from a native code and I have to propagate it to JS 😔 The bug was actually in `useKeyboardInterpolation` hook. Such case, when `onStart` is triggered two times with positive height value is similar to what happens when keyboard size is changed on Android.  And `useKeyboardInterpolation` relies that after keyboard resize we'll get new range `[291, 336]` and keyboard height will be in this range. However it's not the case because real keyboard height will be changing from 0 to 336, and because of that interpolated value will be a negative number.

If I change interpolation mechanism, then we'll see an expected output, because these 2 events are emitted after each other and we'll interpolate to las frame (i. e. from 0 to 336). So in #331 I'm fixing `KeyboardAvoidingView` integration, but I don't think it's possible to fix `useKeyboardHandler` hook just because OS is emitting these events on its own and we don't have any way to verify whether it's valid keyboard frame or not. Does it make sense what I'm saying?

> This is better than it was. If you watch the video, you can see that there are still occasional glitches. We still have duplications of onStart/onEnd handler calls.

Got you. I will try to experiment more to see why these glitches actually happen (I know it's because of duplicated events, but will try to find a way to ignore them somehow)...

**Comment by A-Yatsyk** [comment]
@kirillzyusko yes, thanks, I understand, although it's actually strange that there is an onEnd callback indicating that the keyboard was opened with a height of 291, even though that's not the case, and an update is occurring.

**Comment by A-Yatsyk** [comment]
It would be good to find a way to fix this for KeyboardAvoidingView at least.

**Comment by kirillzyusko** [comment]
@A-Yatsyk I pushed https://github.com/kirillzyusko/react-native-keyboard-controller/pull/331/commits/f18e223e988ec0c7147c10ce2563c70ef0eaf61f - can you again check whether it fixes all the issues?

**Comment by kirillzyusko** [comment]
@A-Yatsyk I pushed a PR with a fix into `main` and the issue got closed automatically. I'll publish a new 1.10.2 version in next hour. If you find that something is not working again (or working incorrectly) - feel free to re-open this issue or submit a new one 🙏 

Thank you for you help in debugging this issue, active participation in resolution and the creation of such descriptive issue ❤️

**Comment by timoisalive** [comment]
Hey @kirillzyusko I'm still facing issues with the keyboard flickering and KeyboardAvoidingView jumping.

I suppose the [root issue](https://github.com/facebook/react-native/issues/39411) is still not fixed in React Native or iOS, but should this library somehow fix the issue?

If I type quick enough, the KeyboardAvoidingView drops and jumps a bit up and down. The previous version of this library seemed to actually work better, it was jumping up/down, but it didn't permanently drop like this.

The "drop" happens also if I focus from the first input to the second.

If I don't use `secureTextEntry` I don't get the Passwords accessory and the behavior is just as I would expect it to be.

https://github.com/user-attachments/assets/732b73af-daa5-457d-85f0-1ac727dce24b

**Comment by kirillzyusko** [comment]
>  The previous version of this library seemed to actually work better

Which version you are referring to? 1.12.7? I think "permanent" drop can be caused by changes in this PR: https://github.com/kirillzyusko/react-native-keyboard-controller/pull/539

Can you please confirm which versions of the library you used?

And maybe you can provide a code snippet from your example so that I can try to use yours code to see whether the problem is actually can be reproduced or not?

**Comment by timoisalive** [comment]
> > The previous version of this library seemed to actually work better
> 
> Which version you are referring to? 1.12.7? I think "permanent" drop can be caused by changes in this PR: #539
> 
> Can you please confirm which versions of the library you used?

I used to have `^1.10.2` but I updated to `^1.13.1`.

> And maybe you can provide a code snippet from your example so that I can try to use yours code to see whether the problem is actually can be reproduced or not?

Below is the form (I'm extending RN components with Shopify Restyle):
```typescript
<Box>
      <Text color="white" fontSize={20} textAlign="center">
        Log in
      </Text>

      <TextInput
        autoCapitalize="none"
        enablesReturnKeyAutomatically
        enterKeyHint="next"
        error={
          formik.touched.usernameOrEmail === true &&
          formik.errors.usernameOrEmail !== undefined
        }
        keyboardType="email-address"
        marginTop="6"
        placeholder="Enter username or email"
        value={formik.values.usernameOrEmail}
        onBlur={formik.handleBlur('usernameOrEmail')}
        onChangeText={formik.handleChange('usernameOrEmail')}
        onSubmitEditing={
          isSubmittable
            ? submitForm
            : () => {
                passwordTextInputRef.current?.focus()
              }
        }
        ref={usernameOrEmailTextInputRef}
      />

      <TextInput
        autoCapitalize="none"
        autoCorrect={false}
        enablesReturnKeyAutomatically
        enterKeyHint="next"
        error={
          formik.touched.password === true &&
          formik.errors.password !== undefined
        }
        marginTop="3"
        placeholder="Enter password"
        ref={passwordTextInputRef}
        secureTextEntry
        value={formik.values.password}
        onBlur={formik.handleBlur('password')}
        onChangeText={formik.handleChange('password')}
        onSubmitEditing={
          isSubmittable
            ? submitForm
            : () => {
                usernameOrEmailTextInputRef.current?.focus()
              }
        }
      />

      <Button
        disabled={!isSubmittable}
        label="Continue"
        marginHorizontal="1"
        marginTop="6"
        showActivity={formik.isSubmitting}
        onPress={submitForm}
      />

      <Button
        label="Forgot password?"
        marginTop="2"
        variant="text"
        onPress={onForgotPasswordPress}
      />

      <Button
        label="Don't have an account?"
        marginTop="12"
        variant="text"
        onPress={onSignUpPress}
      />
    </Box>
    ```

**Comment by kirillzyusko** [comment]
Thanks @timoisalive 

I fixed it in `main` and I'm planning to release it tomorrow. Can you test a new fix tomorrow? 👀

**Comment by kirillzyusko** [comment]
> Awesome, thanks! 🙏 Sure I can! 👍

@timoisalive I published a new release 😊 Would you mind to check it? 👀

**Comment by timoisalive** [comment]
Thanks @kirillzyusko , the update fixed the content from dropping permanently, that's great! 👍

However, it's still jumping a little as you can see on the video. But maybe this is due to the iOS issue and nothing you can do about it... 🤷 


https://github.com/user-attachments/assets/f9433892-9513-4e97-b1e6-78774ffa3490

**Comment by kirillzyusko** [comment]
@timoisalive yeah, in this case jump happens because `inputAccessoryView` gets detached for a fraction of a second and I kind of can not distinguish the root cause of this event - keyboard also can change its size when you switch to emoji keyboard, but from event structure perspective they are identical and I can not distinguish them as "aha, it's a bad one, because it's just a keyboard jump and `inputAccessoryView` will be attached few ms later, so no sense to react on it" vs "okay, it's a resize event triggered by user (i. e. emoji keyboard) we can't ignore that". On your video I can see, how keyboard changes its size and `KeyboardAvoidingView` reacts accordingly:

**Comment by timoisalive** [comment]
You're absolutely right, this is the best approach and definitely good enough for now. Thanks a lot @kirillzyusko for your effort! 🙏
